[Fixed] Writing Unit Tests for Ensemble.py
tasoc/corrections pull request #15
Opened 2019-07-05 14:01 UTC by ojhall94

This PR supersedes #6  but contains the same core changes. 

I need to fix the Travis checks still.

2019-07-09 09:57 UTC, rhandberg requested changes

2019-07-09 09:57 UTC, rhandberg commented on tests/test_tesscorr.py
> +
Add test for CBV as well

2019-07-09 09:57 UTC, rhandberg commented on tests/test_ensemble.py
> +@pytest.mark.skipif(os.environ["USER"] == 'travis',
Change condition to `os.environ.get('CI') == 'true' and os.environ.get('TRAVIS') == 'true'`

2019-07-11 14:06 UTC, rhandberg requested changes

2019-07-11 14:06 UTC, rhandberg commented on tests/test_ensemble.py
> +@pytest.mark.skipif(os.environ["USER"] == 'travis',
Same thing should be changed here...

2019-07-11 14:06 UTC, rhandberg commented on tests/test_ensemble.py
> +@pytest.mark.skipif(os.environ["USER"] == 'travis',
... and here

2019-07-12 15:51 UTC, ojhall94 commented on tests/test_ensemble.py
> +@pytest.mark.skipif(os.environ["USER"] == 'travis',
Oops... done!

2019-07-15 10:54 UTC, rhandberg commented
Hi @ojhall94, have you pushed the last changes? From the "files changed" tab is still looks like there are some leftover `os.environ["USER"] == 'travis'`

2019-07-15 14:46 UTC, ojhall94 commented
Yep you're right, it looks like something funky has happened/is happening to my corrections repository, its not letting me push and telling me cross host redirect is not allowed... I'll try and fix this.

2019-07-15 14:49 UTC, ojhall94 commented
Okay, we're all good. That was weird!

2019-07-16 11:00 UTC, rhandberg approved these changes

2019-07-16 11:00 UTC, merged